# Generated by Django 4.2.1 on 2023-06-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='companyname',
            new_name='company2name',
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company1duration',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company2duration',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company3duration',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company1salary',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company2salary',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='company3salary',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
